### ISSUE TITLE
Text over edge

### ISSUE THREAD

**Issue by diceit** [GiggleLiu/viznet#4]
Hello,
I love this tool.

Could you give me a favor to show an example to display some text over edge?
Thank you.

**Comment by GiggleLiu** [comment]
Good to know someone is using it 😄 
For putting texts over an edge, please refer the first example in this notebook
https://drive.google.com/file/d/1mP9DOoTR4JEhd-ILVXfggpBJOyGatiws/view?usp=sharing

If you are interested in more examples, like putting texts over heads/tails of a line, please let me know.
